/*
 * Port_cfg.h
 *
 *  Created on: Mar 9, 2022
 *      Author: donia
 */

#ifndef PORT_CFG_H_
#define PORT_CFG_H_

#define DEFAULT          		  OUTPUT_LOW


#define PORT_PIN_0_INIT_CFG			INTERNAL_PULLUP
#define PORT_PIN_1_INIT_CFG			DEFAULT
#define PORT_PIN_2_INIT_CFG		    DEFAULT
#define PORT_PIN_3_INIT_CFG		    DEFAULT
#define PORT_PIN_4_INIT_CFG		    DEFAULT
#define PORT_PIN_5_INIT_CFG		    DEFAULT
#define PORT_PIN_6_INIT_CFG		    DEFAULT
#define PORT_PIN_7_INIT_CFG		    DEFAULT


#define PORT_PIN_8_INIT_CFG		    DEFAULT
#define PORT_PIN_9_INIT_CFG		    DEFAULT
#define PORT_PIN_10_INIT_CFG		DEFAULT
#define PORT_PIN_11_INIT_CFG		DEFAULT
#define PORT_PIN_12_INIT_CFG		DEFAULT
#define PORT_PIN_13_INIT_CFG		DEFAULT
#define PORT_PIN_14_INIT_CFG		DEFAULT
#define PORT_PIN_15_INIT_CFG		DEFAULT


#define PORT_PIN_16_INIT_CFG		DEFAULT
#define PORT_PIN_17_INIT_CFG		DEFAULT
#define PORT_PIN_18_INIT_CFG		DEFAULT
#define PORT_PIN_19_INIT_CFG		DEFAULT
#define PORT_PIN_20_INIT_CFG		DEFAULT
#define PORT_PIN_21_INIT_CFG		DEFAULT
#define PORT_PIN_22_INIT_CFG		DEFAULT
#define PORT_PIN_23_INIT_CFG		DEFAULT


#define PORT_PIN_24_INIT_CFG		DEFAULT
#define PORT_PIN_25_INIT_CFG		DEFAULT
#define PORT_PIN_26_INIT_CFG		DEFAULT
#define PORT_PIN_27_INIT_CFG		DEFAULT
#define PORT_PIN_28_INIT_CFG		DEFAULT
#define PORT_PIN_29_INIT_CFG		DEFAULT
#define PORT_PIN_30_INIT_CFG		DEFAULT
#define PORT_PIN_31_INIT_CFG		DEFAULT


#endif /* PORT_CFG_H_ */
